### ISSUE TITLE
How and Where can i configure and install Python ( Build the pip package )

### ISSUE THREAD

**Issue by kerolos** [FloopCZ/tensorflow_cc#122]
I would like to configure the python option with a long with cpp. ( //tensorflow/tools/pip_package:build_pip_package ) to be apple to run the same Tensorflow in python and cpp. 

i added this line   _//tensorflow/tools/pip_package:build_pip_package_ \ in that file **build_tensorflow.sh**

./configure
bazel build -c opt \
            $cuda_config_opts \
            --config=monolithic \
            --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" \
            #--cxx_flag: "-D_MWAITXINTRIN_H_INCLUDED" \
            //tensorflow/tools/pip_package:build_pip_package \
            tensorflow:libtensorflow_cc.so
bazel shutdown

The Error: 
./build_tensorflow.sh: Zeile 75: //tensorflow/tools/pip_package:build_pip_package: Datei oder Verzeichnis nicht gefunden

**Comment by FloopCZ** [comment]
Have you tried the bazel target without the prefix `//` ?

**Comment by jimlloyd** [comment]
@kerolos I want to do this also. My attempt to replicate what you did failed to build the package after a very long build that I left running through the night. I hope that either you or @FloopCZ can help me resolve the problem without needing to go through several iterations of long builds.

My goals is to create a new Docker image essentially the same as the `ubuntu-shared` image, but one that builds the pip package.

I modified the file `/tensorflow_cc/cmake/build_tensorflow.sh.in` as follows:

```
diff --git a/tensorflow_cc/cmake/build_tensorflow.sh.in b/tensorflow_cc/cmake/build_tensorflow.sh.in
index f2f3c8c..9546c21 100755
--- a/tensorflow_cc/cmake/build_tensorflow.sh.in
+++ b/tensorflow_cc/cmake/build_tensorflow.sh.in
@@ -78,5 +78,8 @@ fi
 bazel build --config=opt \
             --config=monolithic \
             $cuda_config_opts \
-            tensorflow:libtensorflow_cc.so
+            tensorflow:libtensorflow_cc.so \
+            tensorflow/tools/pip_package:build_pip_package
 bazel shutdown
```

I then tried to build the Docker image with this command, run from the root of this project:

```
docker build -f Dockerfiles/ubuntu-shared -t jim-tensorflow_cc-unbuntu-shared .
```

@FloopCZ I am unsure whether this above command is how you build the images. As far as I can tell, you leave undocumented exactly how to build the images.

It is this `docker build` that failed in the middle of the night after at least 4 hours of time (on a MacBook).

The build stopped with this error:

```
ERROR: /tensorflow_cc/tensorflow_cc/build/tensorflow/tensorflow/python/keras/api/BUILD:13:1: Executing genrule //tensorflow/python/keras/api:keras_python_api_gen failed (Exit 1)
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/060974257a8d4e8905f83d1f205c7344/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_1_keras_python_api_gen.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 27, in <module>
    from tensorflow.python.tools.api.generator import doc_srcs
  File "/root/.cache/bazel/_bazel_root/060974257a8d4e8905f83d1f205c7344/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_1_keras_python_api_gen.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 83, in <module>
    from tensorflow.python import keras
  File "/root/.cache/bazel/_bazel_root/060974257a8d4e8905f83d1f205c7344/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_1_keras_python_api_gen.runfiles/org_tensorflow/tensorflow/python/keras/__init__.py", line 27, in <module>
    from tensorflow.python.keras import applications
  File "/root/.cache/bazel/_bazel_root/060974257a8d4e8905f83d1f205c7344/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_1_keras_python_api_gen.runfiles/org_tensorflow/tensorflow/python/keras/applications/__init__.py", line 26, in <module>
    from tensorflow.python.keras import layers
  File "/root/.cache/bazel/_bazel_root/060974257a8d4e8905f83d1f205c7344/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_1_keras_python_api_gen.runfiles/org_tensorflow/tensorflow/python/keras/layers/__init__.py", line 37, in <module>
    from tensorflow.python.keras.layers.convolutional import Conv1D
  File "/root/.cache/bazel/_bazel_root/060974257a8d4e8905f83d1f205c7344/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_1_keras_python_api_gen.runfiles/org_tensorflow/tensorflow/python/keras/layers/convolutional.py", line 33, in <module>
    from tensorflow.python.keras.layers.pooling import AveragePooling1D
ModuleNotFoundError: No module named 'tensorflow.python.keras.layers.pooling'
```

The above change to `tensorflow_cc/cmake/build_tensorflow.sh.in` is the only difference from the current `master` of this project.

**Comment by jimlloyd** [comment]
Maybe I have figured out the problem, just a few minutes after posting the above. I assumed that the only change I would need to make is to the `bazel build` command above, but it seems it will also be necessary to install some dependencies, as documented here: https://www.tensorflow.org/install/source

I probably just need to arrange to install these dependencies before starting the build.

```
pip install -U --user pip six numpy wheel setuptools mock 'future>=0.17.1'
pip install -U --user keras_applications --no-deps
pip install -U --user keras_preprocessing --no-deps
```

@FloopCZ: I am somewhat new to both Docker and Bazel. Would it be reasonable to layer the pip build as a separate Docker build on top of the existing ubuntu and archlinux docker images you build? Is that something you could provide with this (excellent!) project?

**Comment by jimlloyd** [comment]
Ok, I realized that it is much simpler just to install the pip package in my Docker image using:

```
RUN pip3 install --user tensorflow==1.13.2
```

This was relatively fast and works fine. No need to build the pip package from source.

Sorry to bother you @kerolos @FloopCZ .
