### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by zaher88abd** [FloopCZ/tensorflow_cc#147]
I am trying to build the library shared version and I am getting this error.
```
cmake -DTENSORFLOW_STATIC=OFF -DTENSORFLOW_SHARED=ON ..
make
```

```
compile_linux_protobuf.sh finished successfully!!!
tensorflow/contrib/makefile/downloads/nsync/builds/default.linux.c++11/nsync.a
Using CUDA from /usr/local/cuda
Using CUDNN from /usr/local/cuda
CUDA support enabled
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
You have bazel 0.16.1 installed.
Traceback (most recent call last):
  File "./configure.py", line 1693, in <module>
    main()
  File "./configure.py", line 1612, in main
    set_tf_nccl_install_path(environ_cp)
  File "./configure.py", line 1208, in set_tf_nccl_install_path
    nccl_lib_path = os.path.join(nccl_install_path, nccl_lib_path)
UnboundLocalError: local variable 'nccl_lib_path' referenced before assignment
CMakeFiles/tensorflow_shared.dir/build.make:106: recipe for target 'tensorflow-stamp/tensorflow_shared-configure' failed
make[2]: *** [tensorflow-stamp/tensorflow_shared-configure] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/tensorflow_shared.dir/all' failed
make[1]: *** [CMakeFiles/tensorflow_shared.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

````

**Comment by FloopCZ** [comment]
I guess it has been fixed here:
https://github.com/tensorflow/tensorflow/commit/62ebf62948554f36401132bf93d821c0b8abc510#diff-ade1d3e4b7c35655f854151d899df62b
I will try to update TF version.

**Comment by borg323** [comment]
A workaround is to set NCCL_INSTALL_PATH.

**Comment by FloopCZ** [comment]
You probably cannot set an empty `nccl_lib_path` variable. Have you tried to put the path to your nccl install path to `NCCL_INSTALL_PATH`?

**Comment by globalmaster** [comment]
> You probably cannot set an empty `nccl_lib_path` variable. Have you tried to put the path to your nccl install path to `NCCL_INSTALL_PATH`?

I have solved this problem. Thanks you!
