### ISSUE TITLE
help building for raspberry pi 4

### ISSUE THREAD

**Issue by yaira24** [FloopCZ/tensorflow_cc#188]
Hi, I'm trying to compile this repository on raspberry pi 4 to get shared lib without Cuda support. I'm using this command: cmake -DTENSORFLOW_STATIC=OFF -DTENSORFLOW_SHARED=ON -DALLOW_CUDA=OFF ..
and get this error:
...
google/protobuf/compiler/csharp/csharp_repeated_message_field.o google/protobuf/compiler/csharp/csharp_repeated_primitive_field.o google/protobuf/compiler/csharp/csharp_source_generator_base.o google/protobuf/compiler/csharp/csharp_wrapper_field.o 
ar: `u' modifier ignored since `D' is the default (see `U') 
libtool: link: ranlib .libs/libprotoc.a 
libtool: link: ( cd ".libs" && rm -f "libprotoc.la" && ln -s "../libprotoc.la" "libprotoc.la" ) 
libtool: link: g++ -pthread -DHAVE_PTHREAD=1 -DHAVE_ZLIB=1 -Wall -Wno-sign-compare -O2 -g -std=c++11 -DNDEBUG -pthread -o .libs/protoc google/protobuf/compiler/main.o ./.libs/libprotobuf.so ./.libs/libprotoc.so -lz -pthread -Wl,-rpath -Wl,/home/pi/tensorflow_cc/tensorflow_cc/build/tensorflow/tensorflow/contrib/makefile/gen/protobuf/lib 
/usr/bin/ld: ./.libs/libprotobuf.so: undefined reference to `__atomic_fetch_add_8' 
collect2: error: ld returned 1 exit status 
make[5]: *** [Makefile:3887: protoc] Error 1 
make[4]: *** [Makefile:1539: all-recursive] Error 1 
make[3]: *** [Makefile:1446: all] Error 2 
make[2]: *** [CMakeFiles/tensorflow_shared.dir/build.make:107: tensorflow-stamp/tensorflow_shared-configure] Error 2 
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/tensorflow_shared.dir/all] Error 2 
make: *** [Makefile:130: all] Error 2

it is possible to compile this repository on raspberry pi 4? 
if Yes how can I address this issue?
thanks, and keep up with the good work on this repository.

**Comment by FloopCZ** [comment]
I would try to add `atomic` somewhere around here: https://github.com/FloopCZ/tensorflow_cc/blob/master/tensorflow_cc/CMakeLists.txt#L138
in order to link to `libatomic`. But not sure, sorry,

**Comment by yaira24** [comment]
thanks, it's solved to this error.
I get a new error related to Bazel(see below) but I install version 0.16.1 like in the documents  "Warning: Newer versions of TensorFlow sometimes fail to build with the latest version of Bazel. You may wish to install an older version of Bazel (e.g., 0.16.1)."
Is this mean that I need to install one of Bazel version 0.19.0 - 0.21.0?

Traceback (most recent call last): 
File "./configure.py", line 1701, in <module> 
main() 
File "./configure.py", line 1557, in main 
check_bazel_version('0.19.0', '0.21.0') 
File "./configure.py", line 457, in check_bazel_version 
['bazel', '--batch', '--bazelrc=/dev/null', 'version']) 
File "./configure.py", line 147, in run_shell 
output = subprocess.check_output(cmd) 
File "/usr/lib/python3.7/subprocess.py", line 395, in check_output 
**kwargs).stdout 
File "/usr/lib/python3.7/subprocess.py", line 487, in run 
output=stdout, stderr=stderr) 
subprocess.CalledProcessError: Command '['bazel', '--batch', '--bazelrc=/dev/null', 'version']' returned non-zero exit status 1.

**Comment by FloopCZ** [comment]
What does your `bazel --version` say? You can try to build TF v1.15  from #189 with bazel 0.26.1, it seems to work properly.

**Comment by FloopCZ** [comment]
Closing for inactivity. You can try `bazel-2.0.0`, it is now a requirement for TF 2.1+.
