### ISSUE TITLE
could someone help build on Mac OS X 10.15

### ISSUE THREAD

**Issue by cxwx** [FloopCZ/tensorflow_cc#210]
error info:

[ 12%] Creating directories for 'tensorflow_base'
[ 25%] Performing download step (git clone) for 'tensorflow_base'
-- Avoiding repeated git clone, stamp file is up to date: '/Users/chenxu/software/tensorflow/git/build/tensorflow-stamp/tensorflow_base-gitclone-lastrun.txt'
[ 37%] No patch step for 'tensorflow_base'
[ 50%] No update step for 'tensorflow_base'
[ 62%] No configure step for 'tensorflow_base'
[ 75%] Performing build step for 'tensorflow_base'
CUDA support disabled
Traceback (most recent call last):
  File "./configure.py", line 1551, in <module>
    main()
  File "./configure.py", line 1368, in main
    _TF_MAX_BAZEL_VERSION)
  File "./configure.py", line 483, in check_bazel_version
    ['bazel', '--batch', '--bazelrc=/dev/null', 'version'])
  File "./configure.py", line 159, in run_shell
    output = subprocess.check_output(cmd, stderr=stderr)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['bazel', '--batch', '--bazelrc=/dev/null', 'version']' returned non-zero exit status 1.
make[2]: *** [tensorflow-stamp/tensorflow_base-build] Error 1
make[1]: *** [CMakeFiles/tensorflow_base.dir/all] Error 2
make: *** [all] Error 2

**Comment by cxwx** [comment]
it should be bazel version problem.
