### ISSUE TITLE
subprocess.CalledProcessError: Command '['bazel', '--batch', '--bazelrc=/dev/null', 'version']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by lanctot** [FloopCZ/tensorflow_cc#216]
Thanks for this, it looks great!

I seem to have a problem building on the `make` step (Ubuntu 20.04):

```
lanctot@nife:~$ git clone https://github.com/FloopCZ/tensorflow_cc.git
Cloning into 'tensorflow_cc'...
remote: Enumerating objects: 113, done.
remote: Counting objects: 100% (113/113), done.
remote: Compressing objects: 100% (74/74), done.
remote: Total 976 (delta 56), reused 74 (delta 37), pack-reused 863
Receiving objects: 100% (976/976), 162.97 KiB | 1005.00 KiB/s, done.
Resolving deltas: 100% (537/537), done.
lanctot@nife:~$ cd tensorflow_cc
lanctot@nife:~/tensorflow_cc$ cd tensorflow_cc
lanctot@nife:~/tensorflow_cc/tensorflow_cc$ mkdir build && cd build
lanctot@nife:~/tensorflow_cc/tensorflow_cc/build$ cmake ..
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/lanctot/tensorflow_cc/tensorflow_cc/build
lanctot@nife:~/tensorflow_cc/tensorflow_cc/build$ make
Scanning dependencies of target tensorflow_base
[ 12%] Creating directories for 'tensorflow_base'
[ 25%] Performing download step (download, verify and extract) for 'tensorflow_base'
-- Downloading...
   dst='/home/lanctot/tensorflow_cc/tensorflow_cc/build/tensorflow/v2.2.0-rc2.tar.gz'
   timeout='none'
-- Using src='https://github.com/tensorflow/tensorflow/archive/v2.2.0-rc2.tar.gz'
-- [download 100% complete]
-- Downloading... done
-- extracting...
     src='/home/lanctot/tensorflow_cc/tensorflow_cc/build/tensorflow/v2.2.0-rc2.tar.gz'
     dst='/home/lanctot/tensorflow_cc/tensorflow_cc/build/tensorflow'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[ 37%] No patch step for 'tensorflow_base'
[ 50%] No update step for 'tensorflow_base'
[ 62%] No configure step for 'tensorflow_base'
[ 75%] Performing build step for 'tensorflow_base'
CUDA support disabled
Traceback (most recent call last):
  File "./configure.py", line 1551, in <module>
    main()
  File "./configure.py", line 1367, in main
    current_bazel_version = check_bazel_version(_TF_MIN_BAZEL_VERSION,
  File "./configure.py", line 482, in check_bazel_version
    curr_version = run_shell(
  File "./configure.py", line 159, in run_shell
    output = subprocess.check_output(cmd, stderr=stderr)
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bazel', '--batch', '--bazelrc=/dev/null', 'version']' returned non-zero exit status 1.
make[2]: *** [CMakeFiles/tensorflow_base.dir/build.make:115: tensorflow-stamp/tensorflow_base-build] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/tensorflow_base.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
lanctot@nife:~/tensorflow_cc/tensorflow_cc/build$ 
```

I know that bazel is accessible via the command-line:

```
lanctot@nife:~/tensorflow_cc/tensorflow_cc/build$ bazel --batch --bazelrc=/dev/null version
Build label: 3.0.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Apr 6 12:52:37 2020 (1586177557)
Build timestamp: 1586177557
Build timestamp as int: 1586177557
lanctot@nife:~/tensorflow_cc/tensorflow_cc/build$ echo $?
0
```

And running it manually via python subprocess also seems to work:

```
lanctot@nife:~/tensorflow_cc/tensorflow_cc/build$ python3
Python 3.8.2 (default, Mar 13 2020, 10:14:16) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import subprocess
>>> output = subprocess.check_output(['bazel', '--batch', '--bazelrc=/dev/null', 'version'])
>>> print(output)
b'Build label: 3.0.0\nBuild target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar\nBuild time: Mon Apr 6 12:52:37 2020 (1586177557)\nBuild timestamp: 1586177557\nBuild timestamp as int: 1586177557\n'
>>> 
```

Any idea why this could be happening?

**Comment by FloopCZ** [comment]
Hi, that is curious, your debugging steps seem proper. The `configure.py` script seems to see the `bazel` binary as well, otherwise it would [terminate sooner](https://github.com/tensorflow/tensorflow/blob/master/configure.py#L479).

Can you try to run the `python3 configure.py` manually from the `tensorflow` folder?

**Comment by lanctot** [comment]
It fails there too.  

But something is really, really messed up. Check this out.. I made a `test.py` in that directory that basically just tries to run subprocess to run the command, which failed for the same reason, which I thought was odd because that simple test was working above. So I changed directories to $HOME and the same tests works from there!

```
lanctot@nife:~/tensorflow_cc/tensorflow_cc/build/tensorflow$ cat test.py
import subprocess
output = subprocess.check_output(['bazel', '--batch', '--bazelrc=/dev/null', 'version'])
print(output)
lanctot@nife:~/tensorflow_cc/tensorflow_cc/build/tensorflow$ python3 test.py 
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    output = subprocess.check_output(['bazel', '--batch', '--bazelrc=/dev/null', 'version'])
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bazel', '--batch', '--bazelrc=/dev/null', 'version']' returned non-zero exit status 1.
lanctot@nife:~/tensorflow_cc/tensorflow_cc/build/tensorflow$ cd ~
lanctot@nife:~$ cat test.py 
import subprocess
output = subprocess.check_output(['bazel', '--batch', '--bazelrc=/dev/null', 'version'])
print(output)
lanctot@nife:~$ python3 test.py 
b'Build label: 3.0.0\nBuild target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar\nBuild time: Mon Apr 6 12:52:37 2020 (1586177557)\nBuild timestamp: 1586177557\nBuild timestamp as int: 1586177557\n'
lanctot@nife:~$ 
lanctot@nife:~$ echo $PYTHONPATH

lanctot@nife:~$ 
```

I  can't explain why it would work in one directory and not the other, my PYTHONPATH is empty. It's not a path thing either because when I point it directly to `/sur/bin/bazel`, it still fails. Either way, I don't think this is a bug in tensorflow_cc. 

I've noticed a similar error with python subprocess (a recurring error) when I first installed Ubuntu 20.04 when upgrading system packages. It eventually went away.  But from a quick googling, seems like other projects have mysterious failures with subprocess and only in Ubuntu 20.04: https://github.com/tklab-tud/ID2T/issues/104

I suspect this is a Python problem on Ubuntu 20.04. I'll try to keep an eye on it and report back if I find a solution.

**Comment by lanctot** [comment]
Ok, I have figured it out. I noticed the directory contained `.bazelrc` and `.bazelversion`. It appears to only happen when those files are in the subdirectory that the command runs in:

```
lanctot@nife:~/tensorflow_cc/tensorflow_cc/build/tensorflow$ python3 test.py 
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    output = subprocess.check_output(['/usr/bin/bazel', '--batch', '--bazelrc=/dev/null', 'version'])
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/bazel', '--batch', '--bazelrc=/dev/null', 'version']' returned non-zero exit status 1.
lanctot@nife:~/tensorflow_cc/tensorflow_cc/build/tensorflow$ 

lanctot@nife:~/tensorflow_cc/tensorflow_cc/build/tensorflow$ mv .bazelrc ~
lanctot@nife:~/tensorflow_cc/tensorflow_cc/build/tensorflow$ mv .bazelversion ~
lanctot@nife:~/tensorflow_cc/tensorflow_cc/build/tensorflow$ python3 test.py 
b'Build label: 3.0.0\nBuild target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar\nBuild time: Mon Apr 6 12:52:37 2020 (1586177557)\nBuild timestamp: 1586177557\nBuild timestamp as int: 1586177557\n'
lanctot@nife:~/tensorflow_cc/tensorflow_cc/build/tensorflow$ 
```

I am not sure how those files got there nor why the call to bazel dies when they are present... A ha! Here is something more useful. When I run it manually in that directory, I get this:

```
ERROR: The project you're trying to build requires Bazel 2.0.0 (specified in /home/lanctot/tensorflow_cc/tensorflow_cc/build/tensorflow/.bazelversion), but it wasn't found in /usr/bin.

You can install the required Bazel version via apt:
  sudo apt update && sudo apt install bazel-2.0.0

If this doesn't work, check Bazel's installation instructions for help:
  https://docs.bazel.build/versions/master/install-ubuntu.html
```

**Comment by lanctot** [comment]
Ok when I install bazel-2.0.0, the make progresses.

It now fails at a different place ... :) Seems to have trouble downloading from `storage.googleapis.com` and I've had connection issues with them before, so I'll just keep at it. 

Closing again!
